### ISSUE TITLE
[BUG] Facebook API V.2.2 was disabled 2017-03-27

### ISSUE THREAD

**Issue by JohannesTyra** [heiseonline/shariff-backend-php#121] opened 2017-03-29 13:36 UTC
The Code / Facebook Request does not work anymore.

 if (null !== $accessToken) {
            $query = 'https://graph.facebook.com/v2.2/?id='.urlencode($url).'&'.$accessToken;
        } else {
            $query = 'https://graph.facebook.com/?id='.urlencode($url);
        }

**Comment by liayn** [comment] 2017-03-29 13:50
Where do you have this information from?

We see errors as well, but those seem to be IP based, since manual requests using the same request still work.

**Comment by JohannesTyra** [comment] 2017-03-29 13:55
I get this message from FB (German).

XXXX  hat derzeit Zugriff auf Graph API v2.2. Diese Version läuft am 27 March, 2017. zum Ende des 2 Jahre gültigen Zeitraums ab. Um einen reibungslosen Übergang sicherzustellen, solltest du alle API-Aufrufe zu Graph API v2.3 oder höher migrieren.

Wenn du herausfinden möchtest, ob deine App von diesem Upgrade betroffen ist, kannst duVersion Upgrade Tool.verwenden. So erfährst du, welche Aufrufe unter Umständen von dieser Änderung betroffen sind und welche in neuen Versionen ersetzt werden. Wenn dir keine Aufrufe angezeigt werden, dann ist deine App von dieser Änderung wahrscheinlich nicht betroffen.

**Comment by JohannesTyra** [comment] 2017-03-29 13:57
The first call with /v2.2 does not work since 27 March, 2017.
The second (old) FQL Call does not work since Nov 2016 I think.

So maybe: $query = 'https://graph.facebook.com/?id='.urlencode($url).'&'.$accessToken;
works?

**Comment by JohannesTyra** [comment] 2017-03-29 14:28
FB Doc:

curl -i -X GET \
 "https://graph.facebook.com/v2.8/?id=http%3A%2F%2Fwww.imdb.com%2Ftitle%2Ftt2015381%2F&access_token=TOKEN"

**Comment by liayn** [comment] 2017-03-29 20:53
Yes, updating would indeed make a lot of sense. Can you push a PR?
Besides that maybe consider also #120

**Comment by JohannesTyra** [comment] 2017-03-30 09:57
Its fixed.
Only this is needed.

        $accessToken = urlencode($this->config['app_id']) .'|'.urlencode($this->config['secret']);
        $query = 'https://graph.facebook.com/v2.8/?id='.urlencode($url).'&access_token='.$accessToken;

        return new \GuzzleHttp\Psr7\Request('GET', $query);

**Comment by liayn** [comment] 2017-03-30 10:04
confirmed!
lets kick the part when no accesstoken is there so #120 is resolved too.

**Comment by JohannesTyra** [comment] 2017-03-30 10:06
Yes. 
And one request less than before (the extra oauth request is not needed)

**Comment by liayn** [comment] 2017-03-30 10:08
preparing PR now

**Comment by compeak** [comment] 2017-03-30 12:46
Fixed in v[7.0.0](https://github.com/heiseonline/shariff-backend-php/releases/tag/7.0.0).

**Closed by compeak** 2017-03-30 12:46 UTC
Labels: enhancement

**Comment by djpytter** [comment] 2017-04-12 10:07
Hello. I have this verion API on muy webpage fbapi.php
 https://github.com/facebookarchive/facebook-php-sdk/blob/master/src/base_facebook.php

Please let me know what to change so I can go on my webpage login with facebook again.
Please:!
